Repository team-gsri/GSRI-Opex, pull requests merged in 2020-04, with the labels that each got.

#13 Fix minor ACE interactions
  addons/gsri_opex/Stringtable.xml
  addons/gsri_opex/config.cpp
  addons/gsri_opex/functions/fremm/fn_fremmAddArsenal.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddHeli.sqf
  addons/gsri_opex/functions/preslots/fn_getEmpty.sqf
Labels: enhancement

#10 Add RKSL+Lesh support and fix backup actions
  addons/gsri_opex/Stringtable.xml
  addons/gsri_opex/functions/fremm/fn_fremmAddHeli.sqf
Labels: enhancement

#19 Fix duplicated RKSL tug
  addons/gsri_opex/functions/fremm/fn_fremmAddHeli.sqf
Labels: bug

#17 Add sqflint check to integration
  .github/workflows/integration.yml
  addons/gsri_opex/functions/fremm/fn_initFremm.sqf
Labels: enhancement, help wanted

#21 Fix local variables that need to be private
  addons/gsri_opex/functions/bays/fn_bayReplace.sqf
  addons/gsri_opex/functions/core/fn_initMission.sqf
  addons/gsri_opex/functions/core/fn_initSettings.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddArsenal.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddBoatBays.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddBridge.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddHeli.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddSub.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddWeapons.sqf
  addons/gsri_opex/functions/fremm/fn_initFremm.sqf
  addons/gsri_opex/functions/heli/fn_heliEquipFRIES.sqf
  addons/gsri_opex/functions/heli/fn_heliRemove.sqf
  addons/gsri_opex/functions/heli/fn_heliRetrieveCurrent.sqf
  addons/gsri_opex/functions/heli/fn_heliSpawn.sqf
  addons/gsri_opex/functions/sub/fn_subSelectPos.sqf
Labels: enhancement

#24 Clean settings parsing for ship features
  addons/gsri_opex/functions/fremm/fn_initFremm.sqf
Labels: bug, enhancement

#25 Allow adding arsenal actions on other objects
  addons/gsri_opex/config.cpp
  addons/gsri_opex/functions/fremm/fn_fremmAddArsenal.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddBoatBays.sqf
  addons/gsri_opex/functions/preslots/fn_setAsLocker.sqf
Labels: enhancement

#32 Add ReadMe
  .github/README.md
Labels: documentation

#29 Propagate medicClass through network
  addons/gsri_opex/functions/preslots/fn_setAsLocker.sqf
Labels: bug

#31 Fix unused variables warnings
  addons/gsri_opex/functions/bays/fn_bayReplace.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddHeli.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddSub.sqf
  addons/gsri_opex/functions/heli/fn_heliEquipFRIES.sqf
  addons/gsri_opex/functions/heli/fn_heliRemove.sqf
  addons/gsri_opex/functions/heli/fn_heliSpawn.sqf
  addons/gsri_opex/functions/sub/fn_subSelectPos.sqf
Labels: enhancement

#38 Add screens to Liberty-class ship
  addons/gsri_opex/config.cpp
  addons/gsri_opex/functions/fremm/fn_fremmAddScreens.sqf
  addons/gsri_opex/functions/fremm/fn_initFremm.sqf
Labels: enhancement

#37 Bay doors
  addons/gsri_opex/Stringtable.xml
  addons/gsri_opex/config.cpp
  addons/gsri_opex/functions/bays/fn_bayDoorControl.sqf
  addons/gsri_opex/functions/fremm/fn_fremmAddBoatBays.sqf
  addons/gsri_opex/functions/heli/fn_heliSpawn.sqf
  addons/gsri_opex/sounds/LICENSE
  addons/gsri_opex/sounds/doorSound.wss
Labels: enhancement
